name: ItemAsylum
version: '${project.version}'
main: io.github.duckysmacky.itemasylum.ItemAsylum
authors: [Ducky]
description: An item asylum gamemode plugin for Minecraft
commands:
  itemasylum:
    description: General help command
    usage: /<command>
  reroll:
    description: Reroll current items
    usage: /<command> <player>
    aliases:
      - r
  game:
    description: Main command for controlling "Item Asylum" game
    usage: /<command>
    aliases:
      - g
  catalog:
    description: View information about item catalog
    usage: /<command>