name: ItemAsylum
version: '0.1.0'
main: io.github.duckysmacky.itemasylum.ItemAsylum
authors: [Ducky]
description: An item asylum gamemode plugin for Minecraft
commands:
  menu:
    description: Game control
    usage: /<command>
    aliases:
      - g