name: ItemAsylum
version: '0.1.0'
main: io.github.duckysmacky.itemasylum.ItemAsylum
authors: [Ducky]
description: An item asylum gamemode plugin for Minecraft
commands:
  game:
    description: Main command for controlling "Item Asylum" gamemode
    usage: /<command>
    aliases:
      - g